name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Suraj"
      - name: Print bye
        run: echo "Done - Bye"
      - name: Multi line commands
        run: |
          echo "line 1"
          echo "line 2"
        
    
